datasets:
  raw:
    sod:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/opportunity_datas/Spring_Oppty_Data.csv
      driver_params: {}

    spd:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/opportunity_datas/springboard_illst_prd_dat.csv
      driver_params: {}
