datasets:
  raw:
    sod:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/opportunity_datas/Spring_Oppty_Data.csv
      driver_params: {}

    spd:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/opportunity_datas/springboard_illst_prd_dat.csv
      driver_params: {}
    
  cleaned:
    opt_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/opt_data.csv
    prd_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/prd_data.csv

  processed:
    merged_df:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/merged_df.csv

     
  # cleaned:
  #   sod:
  #     type: ds
  #     format: parquet
  #     uri: ${core.data_base_path}/cleaned/opportunity_datas/Spring_Oppty_Data.parquet
  #     driver_params: {}

  #   spd:
  #     type: ds
  #     format: parquet
  #     uri: ${core.data_base_path}/cleaned/opportunity_datas/springboard_illst_prd_dat.parquet
  #     driver_params: {}