datasets:
  raw:
    opt_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/opportunity_datas/Spring_Oppty_Data.csv
      driver_params: {}

    prd_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/opportunity_datas/springboard_illst_prd_dat.csv
      driver_params: {}
    merged_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/opportunity_datas/merged_data.csv
      driver_params: {}
    
  cleaned:
    opt_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/opt_data.csv
    prd_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/prd_data.csv

  processed:
    merged_df:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/merged_df.csv
      
    premodel:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/premodel.csv

  train:
    attrition:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/attrition/features.csv   
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/attrition/target.csv 

  test:
    attrition:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/attrition/features.csv   
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/attrition/target.csv 

      
  # cleaned:
  #   sod:
  #     type: ds
  #     format: parquet
  #     uri: ${core.data_base_path}/cleaned/opportunity_datas/Spring_Oppty_Data.parquet
  #     driver_params: {}

  #   spd:
  #     type: ds
  #     format: parquet
  #     uri: ${core.data_base_path}/cleaned/opportunity_datas/springboard_illst_prd_dat.parquet
  #     driver_params: {}